# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: Build
    jobs:
    - job: 'BuildSonarQubeTerraformFiles'

      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/Terraform/SonarQube'
          ArtifactName: 'SonarQube'
          publishLocation: 'Container'

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: 'DeployToAzure'

        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'SonarQube'
              downloadPath: '$(System.ArtifactsDirectory)'
            displayName: 'Download Artifact'